sudo: false
language: python
python:
  - "2.7"
install: 
  - "pip install flake8"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script:
  - flake8
  - coverage run --source=pyIGTLink tests.py
after_success:
  - coveralls
